# Generated by Django 5.2.4 on 2026-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aktivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255)),
                ("tur", models.CharField(max_length=50)),
                ("katilimci_sayisi", models.IntegerField(default=1)),
                ("fiyat_seviyesi", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="BilgiSorusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategori", models.CharField(max_length=100)),
                ("soru", models.TextField()),
                ("dogru_cevap", models.CharField(max_length=200)),
                ("zorluk", models.CharField(max_length=20)),
                ("tip", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="GununUzayResmi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("aciklama", models.TextField()),
                ("url", models.URLField()),
                ("tarih", models.DateField()),
                ("telif", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hayvan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resim", models.URLField()),
                (
                    "tur",
                    models.CharField(
                        choices=[("kedi", "Kedi"), ("kopek", "Köpek")], max_length=10
                    ),
                ),
                ("sevimli_puan", models.IntegerField(default=100)),
                ("eklenme_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meyve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=50)),
                ("kalori", models.FloatField()),
                ("karbonhidrat", models.FloatField()),
                ("seker", models.FloatField()),
                ("yag", models.FloatField()),
                ("protein", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("resim", models.URLField()),
                ("tur", models.CharField(max_length=50)),
                ("guc", models.IntegerField()),
                ("boy", models.FloatField()),
                ("kilo", models.FloatField()),
                ("yetenek", models.CharField(max_length=100)),
                ("can", models.IntegerField(default=50)),
                ("eklenme_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Saka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soru", models.TextField()),
                ("cevap", models.TextField()),
                ("kategori", models.CharField(default="Genel", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SanatEseri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("sanatci", models.CharField(max_length=200)),
                ("resim", models.URLField()),
                ("tarih", models.CharField(blank=True, max_length=100)),
                ("departman", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ulke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("resmi_isim", models.CharField(blank=True, max_length=200)),
                ("baskent", models.CharField(max_length=100)),
                ("bayrak", models.URLField()),
                ("kita", models.CharField(max_length=100)),
                ("nufus", models.BigIntegerField()),
                ("harita_linki", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UzayGorevi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gorev_adi", models.CharField(max_length=200)),
                ("detay", models.TextField(default="Gizli Görev")),
                ("roket_adi", models.CharField(max_length=100)),
                ("firlatma_tarihi", models.CharField(max_length=100)),
                ("resim", models.URLField(blank=True, null=True)),
                ("basari_durumu", models.BooleanField(default=True)),
            ],
        ),
    ]
