# Generated by Django 5.0.8 on 2026-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aktivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255)),
                ("tur", models.CharField(max_length=50)),
                ("katilimci_sayisi", models.IntegerField(default=1)),
                ("fiyat_seviyesi", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="BilgiSorusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategori", models.CharField(max_length=100)),
                ("soru", models.TextField()),
                ("dogru_cevap", models.CharField(max_length=200)),
                ("zorluk", models.CharField(max_length=20)),
                ("tip", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ElSanati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("aciklama", models.TextField(help_text="Sanatın kısa tanımı")),
                ("resim", models.URLField()),
                (
                    "malzemeler",
                    models.CharField(default="Kağıt, Makas", max_length=200),
                ),
                ("zorluk", models.CharField(default="Kolay", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gezegen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("tur", models.CharField(max_length=100)),
                ("resim", models.URLField()),
                ("sicaklik", models.CharField(default="Bilinmiyor", max_length=100)),
                ("yercekimi", models.CharField(default="Normal", max_length=100)),
                ("ozellik", models.TextField(default="Çok gizemli bir gökcismi.")),
            ],
        ),
        migrations.CreateModel(
            name="Hayvan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resim", models.URLField()),
                (
                    "tur",
                    models.CharField(
                        choices=[("kedi", "Kedi"), ("kopek", "Köpek")], max_length=10
                    ),
                ),
                ("sevimli_puan", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Oyun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("resim", models.URLField(help_text="Kapak resmi")),
                ("iframe_url", models.URLField(help_text="Oyunun çalışacağı link")),
                ("kategori", models.CharField(default="Macera", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("resim", models.URLField()),
                ("tur", models.CharField(max_length=50)),
                ("guc", models.IntegerField()),
                ("can", models.IntegerField(default=50)),
                ("boy", models.FloatField(help_text="Metre cinsinden")),
                ("kilo", models.FloatField(help_text="Kilogram cinsinden")),
                (
                    "yetenekler",
                    models.CharField(help_text="Özel yetenekleri", max_length=255),
                ),
                (
                    "ses_dosyasi",
                    models.URLField(blank=True, help_text="Pokemon sesi", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Saka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soru", models.TextField()),
                ("cevap", models.TextField()),
                ("kategori", models.CharField(default="Genel", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SanatEseri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("sanatci", models.CharField(max_length=200)),
                ("resim", models.URLField()),
                ("tarih", models.CharField(blank=True, max_length=100)),
                ("muze_linki", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UzayGorevi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gorev_adi", models.CharField(max_length=200)),
                ("detay", models.TextField(default="Gizli Görev")),
                ("roket_adi", models.CharField(max_length=100)),
                ("firlatma_tarihi", models.CharField(max_length=100)),
                ("resim", models.URLField(blank=True, null=True)),
                ("basari_durumu", models.BooleanField(default=True)),
                ("youtube_link", models.URLField(blank=True, null=True)),
                ("wikipedia_link", models.URLField(blank=True, null=True)),
                (
                    "firlatma_yeri",
                    models.CharField(default="Bilinmiyor", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YemekTarifi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=200)),
                ("resim", models.URLField()),
                ("ozet", models.TextField(help_text="Kısa açıklama")),
                (
                    "malzemeler",
                    models.TextField(
                        default="Malzeme bilgisi yok.",
                        help_text="Virgülle ayrılmış malzemeler",
                    ),
                ),
                (
                    "tarif_detay",
                    models.TextField(
                        default="Tarif hazırlanıyor...", help_text="Adım adım yapılışı"
                    ),
                ),
                ("hazirlama_suresi", models.IntegerField(default=30)),
                ("saglik_puani", models.IntegerField(default=80)),
                ("kalori", models.FloatField(default=0)),
                ("protein", models.CharField(default="0g", max_length=50)),
                ("yag", models.CharField(default="0g", max_length=50)),
                ("karbonhidrat", models.CharField(default="0g", max_length=50)),
                ("seker", models.CharField(default="0g", max_length=50)),
            ],
        ),
    ]
