# Generated by Django 5.0.8 on 2026-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sanateseri",
            old_name="departman",
            new_name="kultur",
        ),
        migrations.RemoveField(
            model_name="hayvan",
            name="eklenme_tarihi",
        ),
        migrations.RemoveField(
            model_name="pokemon",
            name="eklenme_tarihi",
        ),
        migrations.RemoveField(
            model_name="pokemon",
            name="yetenek",
        ),
        migrations.AddField(
            model_name="gununuzayresmi",
            name="hd_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meyve",
            name="aile",
            field=models.CharField(default="Bitki", max_length=100),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="ses_dosyasi",
            field=models.URLField(blank=True, help_text="Pokemon sesi", null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="yetenekler",
            field=models.CharField(
                default=1, help_text="Özel yetenekleri", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sanateseri",
            name="malzeme",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sanateseri",
            name="muze_linki",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="ulke",
            name="alan_kodu",
            field=models.CharField(default="+00", max_length=50),
        ),
        migrations.AddField(
            model_name="ulke",
            name="araba_yonu",
            field=models.CharField(default="Sağ", max_length=10),
        ),
        migrations.AddField(
            model_name="ulke",
            name="diller",
            field=models.CharField(default="Bilinmiyor", max_length=255),
        ),
        migrations.AddField(
            model_name="ulke",
            name="para_birimi",
            field=models.CharField(default="Bilinmiyor", max_length=100),
        ),
        migrations.AddField(
            model_name="uzaygorevi",
            name="firlatma_yeri",
            field=models.CharField(default="Bilinmiyor", max_length=200),
        ),
        migrations.AddField(
            model_name="uzaygorevi",
            name="wikipedia_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uzaygorevi",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="boy",
            field=models.FloatField(help_text="Metre cinsinden"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="kilo",
            field=models.FloatField(help_text="Kilogram cinsinden"),
        ),
    ]
