# Generated by Django 5.0.8 on 2026-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0002_rename_departman_sanateseri_kultur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YemekTarifi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=200)),
                ("resim", models.URLField()),
                ("ozet", models.TextField(help_text="Yemek hakkında kısa bilgi")),
                ("hazirlama_suresi", models.IntegerField(help_text="Dakika cinsinden")),
                ("saglik_puani", models.IntegerField(default=0)),
                ("kalori", models.FloatField(default=0)),
                ("protein", models.CharField(default="0g", max_length=50)),
                ("yag", models.CharField(default="0g", max_length=50)),
                ("karbonhidrat", models.CharField(default="0g", max_length=50)),
                ("seker", models.CharField(default="0g", max_length=50)),
            ],
        ),
    ]
