# Generated by Django 5.0.8 on 2026-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0003_yemektarifi"),
    ]

    operations = [
        migrations.AddField(
            model_name="yemektarifi",
            name="malzemeler",
            field=models.TextField(
                default="Malzeme bilgisi yok.", help_text="Virgülle ayrılmış malzemeler"
            ),
        ),
        migrations.AddField(
            model_name="yemektarifi",
            name="tarif_detay",
            field=models.TextField(
                default="Tarif hazırlanıyor...", help_text="Adım adım yapılışı"
            ),
        ),
        migrations.AlterField(
            model_name="yemektarifi",
            name="hazirlama_suresi",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="yemektarifi",
            name="ozet",
            field=models.TextField(help_text="Kısa açıklama"),
        ),
        migrations.AlterField(
            model_name="yemektarifi",
            name="saglik_puani",
            field=models.IntegerField(default=80),
        ),
    ]
