# Generated by Django 5.0.8 on 2026-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0004_yemektarifi_malzemeler_yemektarifi_tarif_detay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanateseri",
            name="kultur",
        ),
        migrations.RemoveField(
            model_name="sanateseri",
            name="malzeme",
        ),
        migrations.RemoveField(
            model_name="ulke",
            name="alan_kodu",
        ),
        migrations.RemoveField(
            model_name="ulke",
            name="araba_yonu",
        ),
        migrations.RemoveField(
            model_name="ulke",
            name="diller",
        ),
        migrations.RemoveField(
            model_name="ulke",
            name="para_birimi",
        ),
        migrations.AlterField(
            model_name="ulke",
            name="nufus",
            field=models.CharField(max_length=50),
        ),
    ]
