# Generated by Django 5.0.8 on 2026-01-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0005_remove_sanateseri_kultur_remove_sanateseri_malzeme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElSanati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("aciklama", models.TextField(help_text="Sanatın kısa tanımı")),
                ("resim", models.URLField()),
                (
                    "malzemeler",
                    models.CharField(default="Kağıt, Makas", max_length=200),
                ),
                ("zorluk", models.CharField(default="Kolay", max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Ulke",
        ),
    ]
