# Generated by Django 5.0.8 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0006_elsanati_delete_ulke"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarsFotografi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resim", models.URLField()),
                ("kamera", models.CharField(max_length=50)),
                ("tarih", models.CharField(max_length=50)),
            ],
        ),
    ]
