# Generated by Django 5.0.8 on 2026-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0007_marsfotografi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oyun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("resim", models.URLField(help_text="Kapak resmi")),
                ("iframe_url", models.URLField(help_text="Oyunun çalışacağı link")),
                ("kategori", models.CharField(default="Macera", max_length=50)),
            ],
        ),
    ]
