# Generated by Django 5.0.8 on 2026-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0008_oyun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gezegen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("tur", models.CharField(max_length=100)),
                ("resim", models.URLField()),
                ("sicaklik", models.CharField(default="Bilinmiyor", max_length=100)),
                ("yercekimi", models.CharField(default="Normal", max_length=100)),
                ("ozellik", models.TextField(default="Çok gizemli bir gökcismi.")),
            ],
        ),
    ]
