# Generated by Django 5.0.8 on 2026-01-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0009_gezegen"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GununUzayResmi",
        ),
        migrations.DeleteModel(
            name="MarsFotografi",
        ),
        migrations.DeleteModel(
            name="Meyve",
        ),
    ]
